server:
  port: 10086

# datasource
spring:
  datasource:
    url: jdbc:mysql://47.101.133.168:3306/wyu_exam?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 669988
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379


#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: wyu_
  mapper-locations: classpath:/com/mszlu/blog/dao/mapper/*.xml
