server:
  port: 10087
# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wyu0504?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime=120000:

#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: wyu_
  mapper-locations: classpath:/com/mszlu/blog/dao/mapper/*.xml